#include <Arduino.h>
#include "BMWifi.h"
const char banned_html[] PROGMEM = 
"<!DOCTYPE html>\n"
"<html lang=\"en\" dir=\"ltr\">\n"
"\n"
" <head>\n"
" <meta charset=\"utf-8\">\n"
" <title>BRC Open WiFi</title>\n"
" <link rel=\"stylesheet\" href=\"brc.css\">\n"
" <script>\n"
" function myOnload ()\n"
" {\n"
" console.log(\"onload\");\n"
"\n"
" getExpirationTime ();\n"
" }\n"
" </script>\n"
" </head>\n"
" <body onload=\"myOnload()\">\n"
" <script src=\"banned.js\"></script>\n"
"\n"
" <div class=\"top centerHorizontal\" id=\"top\">\n"
" BRC Open WiFi\n"
" </div>\n"
" <div class=\"main centerHorizontal\" id=\"main\">\n"
" This device is currently BANNED for violation of the \n"
" Terms & Conditions which clearly listed \"Dorking about on the internet\" under\n"
" \"Examples of Unacceptable Uses\" as it is a violation of the principle of Immediacy.\n"
" </div>\n"
"\n"
" <div class=\"main centerHorizontal\">\n"
" The ban will expire in <span id=\"expire\">??</span> minutes\n"
" </div>\n"
"\n"
" </body>\n"
"</html>\n"
"\n"
;
