#include <Arduino.h>
#include "BMWifi.h"
const char brc_css[] PROGMEM = 
"/* middle grey style=\"background: #7a7467\" */\n"
"/* light grey style=\"background: #a9a395\" */\n"
"/* dark drey style=\"background: #4e493d\" */\n"
"\n"
"body\n"
"{\n"
" font-family: \"Helvetica Neue\", \"Helvetica\", \"Arial\", \"sans-serif\"; \n"
" font-size: 2em;\n"
"/* background: red; */\n"
"}\n"
"\n"
".centerHorizontal\n"
"{\n"
" margin-left: auto;\n"
" margin-right: auto;\n"
" width: 95%;\n"
"}\n"
"\n"
".top\n"
"{\n"
" font-size: 2em;\n"
" text-align: center;\n"
" background: #7a7467;\n"
" padding-bottom: 0.5em;\n"
" padding-top: 0.5em;\n"
"}\n"
"\n"
"\n"
"/* If screen width >= */\n"
"@media only screen and (min-width: 1000px)\n"
"{\n"
" body\n"
" {\n"
" font-size: 1.5em;\n"
" width: 750px;\n"
" }\n"
" .top\n"
" {\n"
" font-size: 2em;\n"
" }\n"
"}\n"
"\n"
"\n"
".normal\n"
"{\n"
" font-size: 1.5em;\n"
"}\n"
"\n"
".main\n"
"{\n"
" margin-top: 1em;\n"
" margin-bottom: 0.0em;\n"
" font-size: inherit;\n"
"}\n"
"\n"
"\n"
".answers\n"
"{\n"
" background: #a9a395;\n"
" border: 0.15em solid currentColor;\n"
" padding: .1em;\n"
" margin-top: .75em;\n"
" margin-left: 5%;\n"
" margin-right: 5%;\n"
" font-size: 1.75em;\n"
" /* align: center; */\n"
"}\n"
"\n"
;
