#include <Arduino.h>
#include "BMWifi.h"
const char brc_css[] PROGMEM = 
"body\n"
"{\n"
" font-family: Helvetica Neue, Helvetica, Arial, sans-serif;\n"
"}\n"
"\n"
".top\n"
"{\n"
" font-size: 2em;\n"
" font-family: Helvetica Neue, Helvetica, Arial, sans-serif;\n"
" text-align: center;\n"
" "
"background: #a9a395;\n"
" "
"padding-bottom: 0.5em;\n"
" padding-top: 0.5em;\n"
"}\n"
"\n"
"\n"
"/* If screen width <= 700px */\n"
"@media only screen and (max-width: 700px)\n"
"{\n"
" body\n"
" {\n"
" font-size: 2em;\n"
" width: 750px;\n"
" background: red;\n"
" }\n"
"\n"
" .top\n"
" {\n"
" font-size: 2em;\n"
" }\n"
"}\n"
"\n"
"/* If screen width >= 700px */\n"
"@media only screen and (min-width: 700px)\n"
"{\n"
" body\n"
" {\n"
" font-size: 1.5em;\n"
" background: blue;\n"
" width: 750px;\n"
" }\n"
" .top\n"
" {\n"
" font-size: 2em;\n"
" }\n"
"}\n"
"\n"
"\n"
".normal\n"
"{\n"
" font-size: 1.5em;\n"
" font-family: Helvetica Neue, Helvetica, Arial, sans-serif;\n"
"}\n"
"\n"
".main\n"
"{\n"
" margin-top: 1em;\n"
" margin-bottom: 0.0em;\n"
" font-size: inherit;\n"
" font-family: Helvetica Neue, Helvetica, Arial, sans-serif;\n"
"}\n"
"\n"
"\n"
".answers\n"
"{\n"
" margin-top: 1em;\n"
" margin-left: 5%;\n"
" align: center;\n"
"\n"
"}\n"
;
