#include <Arduino.h>
#include "BMWifi.h"
const char debugdata_js[] PROGMEM = 
"questionSet =\n"
"[\n"
" {\n"
" \"question\" : \"You need to demonstrate that you are a burner and not a robot. Which of the following is not one of the Ten Principles?\",\n"
" \"answers\" :\n"
" [\n"
" {\"correct\": true, text : \"Radical Self Entitlement\"},\n"
" {\"correct\": false, text : \"Radical Inclusion\"},\n"
" {\"correct\": false, text : \"Immediacy\"},\n"
" ],\n"
" \"commentary\" : \"Radical Self Entitlement is not a principle.\"\n"
" },\n"
" {\n"
" \"question\": \"Burning Man and the citizens of Black Rock City are dedicated to the Ten Principles. How many principles are there?\",\n"
" \"answers\" :\n"
" [\n"
" {\"correct\": false, text: \"Trick question, there are only nine principles\"},\n"
" {\"correct\": true, text: \"Ten\"},\n"
" {\"correct\": false, text: \"Some other answer\"},\n"
" ],\n"
" \"commentary\" : \"\"\n"
" }\n"
"];\n"
;
