#include <Arduino.h>
#include "BMWifi.h"
const char debugdata_js[] PROGMEM = 
"questionSet =\n"
"[\n"
" {\n"
" \"question\" : \"You need to demonstrate that you are a burner and not a robot. Which of the following is not one of the Ten Principles?\",\n"
" \"answers\" :\n"
" [\n"
" {\"correct\": true, text : \"Radical Self Entitlement\"},\n"
" {\"correct\": false, text : \"Radical Inclusion\"},\n"
" {\"correct\": false, text : \"Immediacy\"},\n"
" ],\n"
" \"commentary\" : \"Radical Self Entitlement is not a principle.\"\n"
" },\n"
" {\n"
" \"question\": \"Burning Man and the citizens of Black Rock City are dedicated to the Ten Principles. How many principles are there?\",\n"
" \"answers\" :\n"
" [\n"
" {\"correct\": false, text: \"Trick question, there are only nine principles\"},\n"
" {\"correct\": true, text: \"Ten\"},\n"
" {\"correct\": false, text: \"Some other answer\"},\n"
" ],\n"
" \"commentary\" : \"\"\n"
" }\n"
"];\n"
"\n"
"currentStatus =\n"
"{\n"
" \"redirects\" : 4,\n"
" \"banned\" : 1,\n"
" \"lastActivity\" : \"1980-01-01\",\n"
" \"sdkVersion\" : \"0\",\n"
" \"bootVersion\" : 0,\n"
" \"chipID\" : \"0\",\n"
" \"cpuFreq\" : 0,\n"
" \"cycleCount\" : 0,\n"
" \"voltage\" : 0,\n"
" \"memoryFree\" : 0,\n"
" \"sketchSize\" : 0,\n"
" \"sketchFree\" : 0,\n"
" \"flashSize\" : 0,\n"
" \"flashSpeed\" : 0,\n"
" \"softApMac\" : \"a\",\n"
" \"softApIP\" : \"127\"\n"
"}\n"
;
