#include <Arduino.h>
#include "BMWifi.h"
const char legal_html[] PROGMEM = 
"<!DOCTYPE html>\n"
"<html lang=\"en\" dir=\"ltr\">\n"
"\n"
"<head>\n"
" <meta charset=\"utf-8\">\n"
" <title>BRC Open WiFi</title>\n"
" <link rel=\"stylesheet\" href=\"brc.css\">\n"
" <link rel=\"stylesheet\" href=\"checkbox.css\">\n"
" <script src=\"questions.js\"></script>\n"
" <style>\n"
" .lic1\n"
" {\n"
" margin:0em 0em 0.5em;\n"
" font-family:Helvetica Neue,Helvetica,Arial,sans-serif;\n"
" line-height:1em;\n"
" }\n"
"\n"
" .licsmall\n"
" {\n"
" font-size:0.9em;\n"
" line-height:1em;\n"
" font-family:Helvetica Neue,Helvetica,Arial,sans-serif;\n"
" }\n"
" .lic18px\n"
" {\n"
" line-height:1em;\n"
" font-family:Helvetica Neue,Helvetica,Arial,sans-serif;\n"
" }\n"
" .liclist\n"
" {\n"
" padding:0em;\n"
" margin:0em 0px 0.5em 2em;\n"
" font-size:0.5em;\n"
" font-family:Helvetica Neue,Helvetica,Arial,sans-serif;\n"
" }\n"
" \n"
" .submit\n"
" {\n"
" font-size: 2em;\n"
" }\n"
" </style>\n"
"\n"
" <script>\n"
" function enable ()\n"
" {\n"
" agreeButton.disabled = !agreeChk.checked;\n"
" }\n"
" </script>\n"
"</head>\n"
"\n"
"<body>\n"
" <div class=\"top centerHorizontal\" id=\"top\">\n"
" <!-- 750x1334 -->\n"
" BRC Open WiFi\n"
" </div>\n"
" <div class=\"main centerHorizontal\" id=\"main\">\n"
" <div dir=\"ltr\">\n"
" <p class=\"lic1\">\n"
" <small class=\"licsmall\"><b>Terms and Conditions</b></small></p>\n"
" <p class=\"licsmall\">\n"
" <small class=\"licsmall\">By using our internet service, you hereby assert that you\n"
" you are a burner and conduct yourself according to the ten priciples. You also acknowledge expressly acknowledge and agree that\n"
" there are significant security, privacy and confidentiality risks inherent in accessing or transmitting information through the internet, whether the connection is facilitated through wired or wireless technology. Security issues include, wi"
"thout limitation, interception of transmissions, loss of data, and the introduction or viruses and other programs that can corrupt or damage your computer.</small></p>\n"
" <p class=\"licsmall\">Accordingly, you agree that the owner and/or provider of this network is NOT liable for any interception or transmissions, computer worms or viruses, loss of data, file corruption, hacking or damage to your computer or other "
"devices that result from the transmission or download of information or materials through the internet service provided.</p>\n"
" <p class=\"licsmall\">Use of the wireless network is subject to the general restrictions outlined below. If abnormal, illegal, or unauthorized behavior is detected, including heavy consumption of bandwidth, the network provider reserves the right "
"to permanently disconnect the offending device from the wireless network.</p>\n"
" <p class=\"licsmall\"><b>Examples of Illegal Uses</b></p>\n"
" <p class=\"licsmall\">The following are representative examples only and do not comprise a comprehensive list of illegal uses:</p>\n"
" <ol class=\"liclist lic18px\">\n"
" <li >Spamming and invasion of privacy - Sending of unsolicited bulk and/or commercial messages over the Internet using the Service or using the Service for activities that invade another's privacy.</li>\n"
" <li >Intellectual property right violations - Engaging in any activity that infringes or misappropriates the intellectual property rights of others, including patents, copyrights, trademarks, service marks, trade secrets, or any other proprie"
"tary right of any third party.</li>\n"
" <li >Accessing illegally or without authorization computers, accounts, equipment or networks belonging to another party, or attempting to penetrate/circumvent security measures of another system. This includes any activity that may be used as"
" a precursor to an attempted system penetration, including, but not limited to, port scans, stealth scans, or other information gathering activity.</li>\n"
" <li >The transfer of technology, software, or other materials in violation of applicable export laws and regulations.</li>\n"
" <li >Export Control Violations</li>\n"
" <li >Using the Service in violation of applicable law and regulation, including, but not limited to, advertising, transmitting, or otherwise making available ponzi schemes, pyramid schemes, fraudulently charging credit cards, pirating softwar"
"e, or making fraudulent offers to sell or buy products, items, or services.</li>\n"
" <li >Uttering threats;</li>\n"
" <li >Distribution of pornographic materials to minors;</li>\n"
" <li >and Child pornography.</li>\n"
" </ol>\n"
" <p class=\"licsmall\"><b>Examples of Unacceptable Uses</b></p>\n"
" <p class=\"licsmall\">The following are representative examples only and do not comprise a comprehensive list of unacceptable uses:</p>\n"
" <ol class=\"liclist lic18px\">\n"
" <li>High bandwidth operations, such as large file transfers and media sharing with peer-to-peer programs (i.e.torrents)</li>\n"
" <li>Obscene or indecent speech or materials</li>\n"
"\n"
"\n"
" <li >High bandwidth operations, such as large file transfers and media sharing with peer-to-peer programs (i.e.torrents)</li>\n"
" <li >Obscene or indecent speech or materials</li>\n"
" <li >Defamatory or abusive language</li>\n"
" <li >Using the Service to transmit, post, upload, or otherwise making available defamatory, harassing, abusive, or threatening material or language that encourages bodily harm, destruction of property or harasses another.</li>\n"
" <li >Forging or misrepresenting message headers, whether in whole or in part, to mask the originator of the message.</li>\n"
" <li >Facilitating a Violation of these Terms of Use</li>\n"
" <li >Hacking</li>\n"
" <li >Distribution of Internet viruses, Trojan horses, or other destructive activities</li>\n"
" <li >Distributing information regarding the creation of and sending Internet viruses, worms, Trojan horses, pinging, flooding, mail-bombing, or denial of service attacks. Also, activities that disrupt the use of or interfere with the ability of "
"others to effectively use the node or any connected network, system, service, or equipment.</li>\n"
" <li >Advertising, transmitting, or otherwise making available any software product, product, or service that is designed to violate these Terms of Use, which includes the facilitation of the means to spam, initiation of pinging, flooding, mail-b"
"ombing, denial of service attacks, and piracy of software.</li>\n"
" <li >The sale, transfer, or rental of the Service to customers, clients or other third parties, either directly or as part of a service or product created for resale.</li>\n"
" <li >Seeking information on passwords or data belonging to another user.</li>\n"
" <li >Making unauthorized copies of proprietary software, or offering unauthorized copies of proprietary software to others.</li>\n"
" <li >Intercepting or examining the content of messages, files or communications in transit on a data network.\n"
" <li >Dorking about on the internet when you should be living in the moment</li>\n"
" </ol></div>\n"
"\n"
"\n"
" <form action=\"question.html\" method=\"post\" class=\"submit\">\n"
" <input type=\"checkbox\" name=\"checktest\" value=\"agree\" id=\"agreeChk\" onclick=\"enable()\">I Understand and Agree<br>\n"
" <input type=\"submit\" value=\"Submit\" id=\"agreeButton\" class=\"main\" onclick=\"getElementById('submitTimeStamp').value = new Date ().toISOString()\" disabled>\n"
" <input type=\"hidden\" id=\"submitTimeStamp\" name=\"timeStamp\" value=\"3487\">\n"
" </form>\n"
" </div>\n"
"\n"
"</body>\n"
"\n"
"</html>\n"
;
