#include <Arduino.h>
#include "BMWifi.h"
const char questions_js[] PROGMEM = 
"{\n"
" var answered = false;\n"
" function answerClick (nextPage, commentary)\n"
" {\n"
" console.log (nextPage);\n"
" console.log (commentary);\n"
" if (answered)\n"
" {\n"
" window.location.href = nextPage;\n"
" }\n"
" else\n"
" {\n"
" answered = true;\n"
" var correct = 0;\n"
" answerButton.innerHTML = \"Next\";\n"
" const inputs = document.getElementsByTagName (\"input\");\n"
" if (inputs != null)\n"
" {\n"
" for (var i=0; i<inputs.length; i++)\n"
" {\n"
" inputs[i].disabled = true;\n"
" if (inputs[i].dataset.correct == \"true\")\n"
" {\n"
" if (inputs[i].checked)\n"
" correct = 1;\n"
" inputs[i].parentNode.style.opacity = \"1.0\";\n"
" }\n"
" else\n"
" inputs[i].parentNode.style.opacity = \"0.1\";\n"
" }\n"
" }\n"
"\n"
" if (correct)\n"
" solution.innerHTML = \"Correct\";\n"
" else\n"
" solution.innerHTML = \"Sorry\";\n"
"\n"
" if (commentary != \"\")\n"
" solution.innerHTML += \" - \" + commentary;\n"
" }\n"
" }\n"
"\n"
" function selectionChanged ()\n"
" {\n"
" answerButton.disabled = false;\n"
" }\n"
"\n"
" "
"function shuffleArray (array)\n"
" {\n"
" for (var i = array.length - 1; i > 0; i--)\n"
" {\n"
" var j = Math.floor(Math.random() * (i + 1));\n"
" var temp = array[i];\n"
" array[i] = array[j];\n"
" array[j] = temp;\n"
" }\n"
" }\n"
"}\n"
;
