#include <Arduino.h>
const char question2_html[] PROGMEM = "</<!DOCTYPE html>"
"<html lang=\"en\" dir=\"ltr\">"
""
" <head>"
" <meta charset=\"utf-8\">"
" <title>BRC Open Wi Fi</title>"
" <link rel=\"stylesheet\" type=\"text/css\" href=\"BRC.css\" />"
" <script type=\"text/javascript\" src=\"questions.js\"></script>"
" </head>"
""
" <body>"
" <div class=\"top\">"
" BRC Open WiFi"
" </div>"
" <div class=\"main\">"
" Burning Man and the citizens of Black Rock City are dedicated to the Ten Principles."
" How many principles are there?"
" <div class=\"answers\">"
" <div style=\"background: #7a7467\" id=\"o1\">"
" <input type=\"radio\" id=\"option1\" name=\"answer\" value=\"1\" onclick=\"selectionChanged()\"/>"
" <label for=\"option1\">Trick question, there are only nine principles</label>"
" </div>"
" <div style=\"background: #a9a395\" id=\"o2\">"
" <input type=\"radio\" id=\"option2\" name=\"answer\" value=\"2\" data-correct=\"1\" onclick=\"selectionChanged()\"/>"
" <label for=\"option2\">Ten</label>"
" </div>"
" <div style=\"background: #4e493d\" id=\"o3\">"
" <input type=\"radio\" id=\"option3\" name=\"answer\" value=\"3\" onclick=\"selectionChanged()\"/>"
" <label for=\"option3\">I don't know</label>"
" </div>"
" </div>"
" <div class=\"main\">"
" <button class=\"normal\" id=\"answer\" onclick=\"answerClick('question3.html')\" disabled=\"true\" value=\"Sub\">Answer</button> <span id=\"solution\" class=\"normal\"></span>"
" </div>"
""
" </div>"
" </body>"
"</html>"
""
"";
