#include <Arduino.h>
#include "BMWifi.h"
const char question_html[] PROGMEM = 
"<!DOCTYPE html>\n"
"<html lang=\"en\" dir=\"ltr\">\n"
" <!-- developer.mozilla.org/en-US/docs/Web/Guide/AJAX/Getting_Started -->\n"
" <head>\n"
" <meta charset=\"utf-8\">\n"
" <title>BRC Open WiFi</title>\n"
" <link rel=\"stylesheet\" href=\"brc.css\">\n"
" <link rel=\"stylesheet\" href=\"radio2.css\">\n"
" <script src=\"questions.js\"></script>\n"
" <script src=\"debugdata.js\"></script>\n"
" <script>\n"
" function myOnload ()\n"
" {\n"
" let questionNumber = 0;\n"
" console.log(\"onload\");\n"
"\n"
" questionNumber = getQuestionNumber ();\n"
" console.log (\"This is question \" + questionNumber);\n"
"\n"
" getQuestionSet ();\n"
"\n"
" /* solution.innerHTML = \"Screen \" + screen.width + \"x\"+ screen.height; */\n"
" }\n"
" </script>\n"
" </head>\n"
"\n"
" <body onload=\"myOnload()\">\n"
" <div class=\"top centerHorizontal\" id=\"top\">\n"
" BRC Open WiFi\n"
" </div>\n"
" <div class=\"main centerHorizontal\" id=\"main\">\n"
" <div id=\"questionDiv\">\n"
" Loading question set.\n"
" </div>\n"
" <div class=\"answers\">\n"
" <div id=\"optdiv0\" hidden>\n"
" <input type=\"radio\" id=\"optinput0\" name=\"answer\" value=\"0\" onclick=\"selectionChanged()\"/>\n"
" <label id=\"optlabel0\" for=\"optinput0\">0</label>\n"
" </div>\n"
" <div id=\"optdiv1\" hidden>\n"
" <input type=\"radio\" id=\"optinput1\" name=\"answer\" value=\"1\" onclick=\"selectionChanged()\"/>\n"
" <label id=\"optlabel1\" for=\"optinput1\">1</label>\n"
" </div>\n"
" <div id=\"optdiv2\" hidden>\n"
" <input type=\"radio\" id=\"optinput2\" name=\"answer\" value=\"2\" onclick=\"selectionChanged()\"/>\n"
" <label id=\"optlabel2\" for=\"optinput2\">2</label>\n"
" </div>\n"
" <div id=\"optdiv3\" hidden>\n"
" <input type=\"radio\" id=\"optinput3\" name=\"answer\" value=\"3\" onclick=\"selectionChanged()\"/>\n"
" <label id=\"optlabel3\" for=\"optinput3\">3</label>\n"
" </div>\n"
" <div id=\"optdiv4\" hidden>\n"
" <input type=\"radio\" id=\"optinput4\" name=\"answer\" value=\"4\" onclick=\"selectionChanged()\"/>\n"
" <label id=\"optlabel4\" for=\"optinput4\">3</label>\n"
" </div>\n"
" </div>\n"
" <div class=\"main\">\n"
" <button class=\"normal\" id=\"answerButton\" onclick=\"answerClick(getNextPage(),commentary)\" disabled value=\"Sub\">Answer</button> <span id=\"solution\" class=\"normal\"></span>\n"
" </div>\n"
" </div>\n"
" </body>\n"
"</html>\n"
;
