#include <Arduino.h>
#include "BMWifi.h"
const char question_html[] PROGMEM = 
"<!DOCTYPE html>\n"
"<html lang=\"en\" dir=\"ltr\">\n"
" <!-- developer.mozilla.org/en-US/docs/Web/Guide/AJAX/Getting_Started -->\n"
" <head>\n"
" <meta charset=\"utf-8\">\n"
" <title>BRC Open WiFi</title>\n"
" <link rel=\"stylesheet\" type=\"text/css\" href=\"brc.css\" />\n"
" <script type=\"text/javascript\" src=\"questions.js\"></script>\n"
" <script type=\"text/javascript\">\n"
" var questionSet =\n"
" [\n"
" {\n"
" \"question\" : \"You need to demonstrate that you are a burner and not a robot. Which of the following is not one of the Ten Principles?\",\n"
" \"answers\" :\n"
" [\n"
" {\"correct\": true, text : \"Radical Self Entitlement\"},\n"
" {\"correct\": false, text : \"Radical Inclusion\"},\n"
" {\"correct\": false, text : \"Immediacy\"},\n"
" ],\n"
" \"commentary\" : \"Radical Self Entitlement is not a principle.\"\n"
" },\n"
" {\n"
" \"question\": \"Burning Man and the citizens of Black Rock City are dedicated to the Ten Principles. How many principles are there?\",\n"
" \"answers\" :\n"
" [\n"
" {\"correct\": false, text: \"Trick question, there are only nine principles\"},\n"
" {\"correct\": true, text: \"Ten\"},\n"
" {\"correct\": false, text: \"Some other answer\"},\n"
" ],\n"
" \"commentary\" : \"\"\n"
" }\n"
" ];\n"
"\n"
" var nextQuestionPage;\n"
"\n"
" function getQuestionNumber ()\n"
" {\n"
" var qn = 0;\n"
" const queryString = window.location.search;\n"
" const urlParams = new URLSearchParams (window.location.search);\n"
" if (urlParams.get ('q') != null)\n"
" qn = Number (urlParams.get ('q'));\n"
"\n"
" if (isNaN (qn) || (qn < 0)|| (qn > (questionSet.length-1)))\n"
" qn = 0;\n"
"\n"
" return qn\n"
" }\n"
"\n"
" const xhr = new XMLHttpRequest();\n"
" function someHandler ()\n"
" {\n"
" if (xhr.readyState === XMLHttpRequest.DONE)\n"
" {\n"
" if (xhr.status === 200)\n"
" {\n"
" var data = JSON.parse (xhr.responseText);\n"
" questionSet = data;\n"
" displayQuestion (getQuestionNumber());\n"
" }\n"
" else\n"
" {\n"
" "
"}\n"
" }\n"
" }\n"
"\n"
" function getQuestionSet (qNumber)\n"
" {\n"
" const url = 'getJson';\n"
"\n"
" var formData = new FormData();\n"
"\n"
" formData.append (\"question\", qNumber);\n"
"\n"
" xhr.open ('POST', url, true);\n"
" xhr.onreadystatechange = someHandler;\n"
" xhr.send (formData);\n"
" }\n"
"\n"
" function displayQuestion (qn)\n"
" {\n"
" let questionData = questionSet[qn];\n"
"\n"
" answers = questionData.answers;\n"
" commentary = questionData.commentary;\n"
" questionDiv.innerText = questionData.question;\n"
"\n"
" for (let i=0; i<10; i++)\n"
" {\n"
" let optdiv = document.getElementById (\"optdiv\" + i);\n"
" if (optdiv != null)\n"
" optdiv.hidden = true;\n"
" }\n"
"\n"
" for (let i=0; i<answers.length; i++)\n"
" {\n"
" let optdiv = document.getElementById (\"optdiv\" + i);\n"
" let optlabel = document.getElementById (\"optlabel\" + i);\n"
" let optinput = document.getElementById (\"optinput\" + i);\n"
" if (optdiv != null)\n"
" {\n"
" optdiv.hidden = false;\n"
" optlabel.innerText = answers[i].text;\n"
" optinput.dataset.correct = answers[i].correct;\n"
" if (optinput.dataset.correct == \"true\")\n"
" optdiv.style.color = \"blue\";\n"
" }\n"
" }\n"
" }\n"
"\n"
" function myOnload ()\n"
" {\n"
" var questionNumber = 0;\n"
" console.log(\"onload\");\n"
"\n"
" questionNumber = getQuestionNumber ();\n"
" var nextNumber = 1 + questionNumber;\n"
" console.log (\"This is question \" + questionNumber);\n"
" console.log (\"Next is \", nextNumber);\n"
"\n"
" if (nextNumber >= questionSet.length)\n"
" nextQuestionPage = \"blocked.html\";\n"
" else\n"
" nextQuestionPage = \"question.html?q=\"+nextNumber;\n"
"\n"
" getQuestionSet ();\n"
" }\n"
" </script>\n"
" </head>\n"
"\n"
" <body onload=\"myOnload()\">\n"
" <div class=\"top\" id=\"top\">\n"
" BRC Open WiFi\n"
" </div>\n"
" <div class=\"main\" id=\"main\">\n"
" <div id=\"questionDiv\">\n"
" You need to demonstrate that you are a burner and not a robot.\n"
" Which of the following is not one of the Ten Principles?\n"
" </div>\n"
" <div class=\"answers\">\n"
" <div style=\"background: #7a7467\" id=\"optdiv0\" hidden=\"true\">\n"
" <input type=\"radio\" id=\"optinput0\" name=\"answer\" value=\"0\" onclick=\"selectionChanged()\"/>\n"
" <label id=\"optlabel0\" for=\"optinput0\">0</label>\n"
" </div>\n"
" <div style=\"background: #a9a395\" id=\"optdiv1\" hidden=\"true\">\n"
" <input type=\"radio\" id=\"optinput1\" name=\"answer\" value=\"1\" onclick=\"selectionChanged()\"/>\n"
" <label id=\"optlabel1\" for=\"optinput1\">1</label>\n"
" </div>\n"
" <div style=\"background: #4e493d\" id=\"optdiv2\" hidden=\"true\">\n"
" <input type=\"radio\" id=\"optinput2\" name=\"answer\" value=\"2\" onclick=\"selectionChanged()\"/>\n"
" <label id=\"optlabel2\" for=\"optinput2\">2</label>\n"
" </div>\n"
" <div id=\"optdiv3\" hidden=\"true\">\n"
" <input type=\"radio\" id=\"optinput3\" name=\"answer\" value=\"3\" onclick=\"selectionChanged()\"/>\n"
" <label id=\"optlabel3\" for=\"optinput3\">3</label>\n"
" </div>\n"
" </div>\n"
" <div class=\"main\">\n"
" <button class=\"normal\" id=\"answerButton\" onclick=\"answerClick(nextQuestionPage,commentary)\" disabled=\"true\" value=\"Sub\">Answer</button> <span id=\"solution\" class=\"normal\"></span>\n"
" </div>\n"
" </div>\n"
" </body>\n"
"</html>\n"
;
