#include <Arduino.h>
#include "BMWifi.h"
const char questions_js[] PROGMEM = 
"{\n"
" var questionSet;\n"
" var answered = false;\n"
" function answerClick (nextPage, commentary)\n"
" {\n"
" console.log (nextPage);\n"
" console.log (commentary);\n"
" if (answered)\n"
" {\n"
" window.location.href = nextPage;\n"
" }\n"
" else\n"
" {\n"
" answered = true;\n"
" var correct = 0;\n"
" answerButton.innerHTML = \"Next\";\n"
" const inputs = document.getElementsByTagName (\"input\");\n"
" if (inputs != null)\n"
" {\n"
" for (var i=0; i<inputs.length; i++)\n"
" {\n"
" inputs[i].disabled = true;\n"
" if (inputs[i].dataset.correct == \"true\")\n"
" {\n"
" if (inputs[i].checked)\n"
" correct = 1;\n"
" inputs[i].parentNode.style.opacity = \"1.0\";\n"
" }\n"
" else\n"
" inputs[i].parentNode.style.opacity = \"0.1\";\n"
" }\n"
" }\n"
"\n"
" if (correct)\n"
" solution.innerHTML = \"Correct\";\n"
" else\n"
" solution.innerHTML = \"Sorry\";\n"
"\n"
" if (commentary != \"\")\n"
" solution.innerHTML += \" - \" + commentary;\n"
" }\n"
" }\n"
"\n"
" function selectionChanged ()\n"
" {\n"
" answerButton.disabled = false;\n"
" }\n"
"\n"
"\n"
" var nextQuestionPage;\n"
"\n"
" function getQuestionNumber ()\n"
" {\n"
" var qn = 0;\n"
" const queryString = window.location.search;\n"
" const urlParams = new URLSearchParams (window.location.search);\n"
" if (urlParams.get ('q') != null)\n"
" qn = Number (urlParams.get ('q'));\n"
"\n"
" if (isNaN (qn) || (qn < 0) || (questionSet == null) || (qn > (questionSet.length-1)))\n"
" qn = 0;\n"
"\n"
" return qn\n"
" }\n"
"\n"
" function getNextPage ()\n"
" {\n"
" let nextNumber = 1 + getQuestionNumber ();\n"
" let nextQuestionPage = \"question.html?q=\"+nextNumber;\n"
"\n"
" if (nextNumber >= questionSet.length)\n"
" nextQuestionPage = \"blocked.html\";\n"
"\n"
" return nextQuestionPage;\n"
" }\n"
"\n"
" const xhr = new XMLHttpRequest();\n"
" function ajaxHandler ()\n"
" {\n"
" if (xhr.readyState === XMLHttpRequest.DONE)\n"
" {\n"
" if (xhr.status === 200)\n"
" {\n"
" var data = JSON.parse (xhr.responseText);\n"
" questionSet = data;\n"
" displayQuestion (getQuestionNumber());\n"
" }\n"
" else\n"
" {\n"
" //alert('There was a problem with the request: ' + xhr.status);\n"
" }\n"
" }\n"
" }\n"
"\n"
" function getQuestionSet (qNumber)\n"
" {\n"
" displayQuestion (getQuestionNumber());\n"
"\n"
" if (window.location.protocol == \"file:\")\n"
" {\n"
" displayQuestion (getQuestionNumber());\n"
" }\n"
" else\n"
" {\n"
" const url = 'getJson';\n"
" var formData = new FormData();\n"
" formData.append (\"request\", \"question\");\n"
"\n"
" xhr.open ('POST', url, true);\n"
" xhr.onreadystatechange = ajaxHandler;\n"
" xhr.send (formData);\n"
" }\n"
" }\n"
"\n"
"\n"
" function displayQuestion (qn)\n"
" {\n"
" let questionData = questionSet[qn];\n"
"\n"
" answers = questionData.answers;\n"
" commentary = questionData.commentary;\n"
" questionDiv.innerText = questionData.question;\n"
"\n"
" for (let i=0; i<10; i++)\n"
" {\n"
" let optdiv = document.getElementById (\"optdiv\" + i);\n"
" if (optdiv != null)\n"
" optdiv.hidden = true;\n"
" }\n"
"\n"
" for (let i=0; i<answers.length; i++)\n"
" {\n"
" let optdiv = document.getElementById (\"optdiv\" + i);\n"
" let optlabel = document.getElementById (\"optlabel\" + i);\n"
" let optinput = document.getElementById (\"optinput\" + i);\n"
" if (optdiv != null)\n"
" {\n"
" optdiv.hidden = false;\n"
" optlabel.innerText = answers[i].text;\n"
" optinput.dataset.correct = answers[i].correct;\n"
"// if (optinput.dataset.correct == \"true\")\n"
"// optdiv.style.color = \"blue\";\n"
" }\n"
" }\n"
" }\n"
"\n"
"\n"
" // Randomize array in-place using Durstenfeld shuffle algorithm\n"
" function shuffleArray (array)\n"
" {\n"
" for (var i = array.length - 1; i > 0; i--)\n"
" {\n"
" var j = Math.floor(Math.random() * (i + 1));\n"
" var temp = array[i];\n"
" array[i] = array[j];\n"
" array[j] = temp;\n"
" }\n"
" }\n"
"}\n"
;
