#include <Arduino.h>

static const char questions_js[] PROGMEM =  "{"
" var answered = false;"
" function answerClick (nextPage)"
" {"
" if (answered)"
" {"
" window.location.href = nextPage;"
" }"
" else"
" {"
" answered = true;"
" var correct = 0;"
" answer.innerHTML = \"Next\";"
" const inputs = document.getElementsByTagName (\"input\");"
" if (inputs != null)"
" {"
" for (var i=0; i<inputs.length; i++)"
" {"
" inputs[i].disabled = true;"
" if ((inputs[i].dataset.correct == \"1\") &&"
" inputs[i].checked)"
" correct = 1;"
" if (inputs[i].dataset.correct == \"1\")"
" inputs[i].parentNode.style.opacity = \"1.0\";"
" else"
" inputs[i].parentNode.style.opacity = \"0.1\";"
" }"
" }"
""
""
" if (correct)"
" solution.innerHTML = \"Correct\";"
" else"
" solution.innerHTML = \"Sorry\";"
" }"
" }"
""
" function selectionChanged ()"
" {"
" answer.disabled = false;"
" }"
""
" /* Randomize array in-place using Durstenfeld shuffle algorithm */"
" function shuffleArray(array) "
" {"
" for (var i = array.length - 1; i > 0; i--) "
" {"
" var j = Math.floor(Math.random() * (i + 1));"
" var temp = array[i];"
" array[i] = array[j];"
" array[j] = temp;"
" }"
" }"
"}"
"";

const char *questionsjs ()
{
   return questions_js;
}
