#include <Arduino.h>
#include "BMWifi.h"
const char status_js[] PROGMEM = 
"{\n"
"var questionSet;\n"
"var currentStatus;\n"
"\n"
" const xhr = new XMLHttpRequest();\n"
" function ajaxHandler ()\n"
" {\n"
" if (xhr.readyState === XMLHttpRequest.DONE)\n"
" {\n"
" if (xhr.status === 200)\n"
" {\n"
" var data = JSON.parse (xhr.responseText);\n"
" currentStatus = data;\n"
" displayStatus ();\n"
" }\n"
" else\n"
" {\n"
" //alert('There was a problem with the request: ' + xhr.status);\n"
" }\n"
" }\n"
" }\n"
"\n"
"\n"
"\n"
" function getStatus ()\n"
" {\n"
" if (window.location.protocol == \"file:\")\n"
" {\n"
" displayStatus ();\n"
" }\n"
" else\n"
" {\n"
" const url = 'getJson';\n"
" var formData = new FormData();\n"
" formData.append (\"request\", \"status\");\n"
"\n"
" xhr.open ('POST', url, true);\n"
" xhr.onreadystatechange = ajaxHandler;\n"
" xhr.send (formData);\n"
" }\n"
" }\n"
"\n"
"\n"
"\n"
" function displayStatus ()\n"
" {\n"
" document.getElementById (\"requests\").innerText = currentStatus.redirects;\n"
" document.getElementById (\"banned\").innerText = currentStatus.banned;\n"
" document.getElementById (\"lastActivity\").innerText = currentStatus.lastActivity;\n"
"\n"
" document.getElementById (\"sdkVersion\").innerText = currentStatus.sdkVersion;\n"
" document.getElementById (\"bootVersion\").innerText = currentStatus.bootVersion;\n"
" document.getElementById (\"chipID\").innerText = currentStatus.chipID;\n"
" document.getElementById (\"cpuFreq\").innerText = currentStatus.cpuFreq;\n"
" document.getElementById (\"cycleCount\").innerText = currentStatus.cycleCount;\n"
" document.getElementById (\"voltage\").innerText = currentStatus.voltage;\n"
" document.getElementById (\"memoryFree\").innerText = currentStatus.memoryFree;\n"
" document.getElementById (\"sketchSize\").innerText = currentStatus.sketchSize;\n"
" document.getElementById (\"sketchFree\").innerText = currentStatus.sketchFree;\n"
" document.getElementById (\"flashSpeed\").innerText = currentStatus.flashSpeed;\n"
" document.getElementById (\"flashSize\").innerText = currentStatus.flashSize;\n"
" document.getElementById (\"softApMac\").innerText = currentStatus.softApMac;\n"
" document.getElementById (\"softApIP\").innerText = currentStatus.softApIP;\n"
"\n"
" }\n"
"}"
;
