#include <Arduino.h>
#include "BMWifi.h"
const char status_html[] PROGMEM = 
"<!DOCTYPE html>\n"
"<html lang=\"en\" dir=\"ltr\">\n"
" <!-- developer.mozilla.org/en-US/docs/Web/Guide/AJAX/Getting_Started -->\n"
" <head>\n"
" <meta charset=\"utf-8\">\n"
" <title>BRC Open WiFi</title>\n"
" <link rel=\"stylesheet\" href=\"brc.css\">\n"
" <link rel=\"stylesheet\" href=\"radio2.css\">\n"
" <script src=\"status.js\"></script>\n"
" <script src=\"debugdata.js\"></script>\n"
" <script>\n"
" function myOnload ()\n"
" {\n"
" console.log(\"onload\");\n"
" getStatus ();\n"
" }\n"
" </script>\n"
" </head>\n"
"\n"
" <body onload=\"myOnload()\">\n"
" <div class=\"top centerHorizontal\" id=\"top\">\n"
" BRC Open WiFi\n"
" </div>\n"
" <div class=\"main centerHorizontal\" id=\"main\">\n"
" <table>\n"
" <tr><td>Requests: </td><td id=\"requests\"></td></tr>\n"
" <tr><td>Banned: </td><td id=\"banned\"></td></tr>\n"
" <tr><td>Last Activity: </td><td id=\"lastActivity\"></td></tr>\n"
" <tr><td>&nbsp;</td> </tr>\n"
" <tr><td>SDK Version: </td><td id=\"sdkVersion\"></td></tr>\n"
" <tr><td>Boot Version: </td><td id=\"bootVersion\"></td></tr>\n"
" <tr><td>Chip ID: </td><td id=\"chipID\"></td></tr>\n"
" <tr><td>CPU Freq: </td><td id=\"cpuFreq\"></td></tr>\n"
" <tr><td>Voltage: </td><td id=\"voltage\"></td></tr>\n"
" <tr><td>Free Heap: </td><td id=\"memoryFree\"></td></tr>\n"
" <tr><td>Sketch Size: </td><td id=\"sketchSize\"></td></tr>\n"
" <tr><td>Sketch Free: </td><td id=\"sketchFree\"></td></tr>\n"
" <tr><td>Flash Size: </td><td id=\"flashSize\"></td></tr>\n"
" <tr><td>Soft AP Mac: </td><td id=\"softApMac\"></td></tr>\n"
" <tr><td>Soft AP IP: </td><td id=\"softApIP\"></td></tr>\n"
" </table>\n"
" </div>\n"
"\n"
" </body>\n"
"</html>\n"
;
