#include <Arduino.h>
#include "BMWiFi.h"


const char blocked_html[] PROGMEM = 
"<!DOCTYPE html>\n"
"<html lang=\"en\" dir=\"ltr\">\n"
"\n"
" <head>\n"
" <meta charset=\"utf-8\">\n"
" <title>BRC Open WiFi</title>\n"
" <link rel=\"stylesheet\" href=\"brc.css\">\n"
" <script src=\"bmwifi.js\"></script>\n"
" <script>\n"
" function myOnload ()\n"
" {\n"
" console.log(\"onload\");\n"
" let title = getCookie (\"title\");\n"
" document.title = title;\n"
" setElementInnerText (\"top\", title);\n"
" }\n"
" </script> \n"
" </head>\n"
" <body onload=\"myOnload()\">\n"
" <script src=\"questions.js\"></script>\n"
"\n"
" <div class=\"top centerHorizontal\" id=\"top\">\n"
" BRC Open WiFi\n"
" </div>\n"
" <div class=\"banned centerHorizontal\" id=\"main\">\n"
" Thank you for showing that you are not a robot. Access to internet services is DENIED due to\n"
" violations of the Terms & Conditions which clearly listed \"Dorking about on the internet\" under\n"
" \"Examples of Unacceptable Uses\" as it is a violation of the principle of Immediacy.\n"
" </div>\n"
"\n"
" <div class=\"main centerHorizontal\" id=\"blocked\">\n"
" Your device ID has been added to the banned list.\n"
" </div>\n"
" </body>\n"
"</html>\n"
;


const char brc_css[] PROGMEM = 
"/* middle grey style=\"background: #7a7467\" */\n"
"/* light grey style=\"background: #a9a395\" */\n"
"/* dark drey style=\"background: #4e493d\" */\n"
"\n"
"body\n"
"{\n"
" font-family: \"Helvetica Neue\", \"Helvetica\", \"Arial\", \"sans-serif\"; \n"
" font-size: 2em;\n"
"/* background: red; */\n"
"}\n"
"\n"
".centerHorizontal\n"
"{\n"
" margin-left: auto;\n"
" margin-right: auto;\n"
" width: 95%;\n"
"}\n"
"\n"
".top\n"
"{\n"
" font-size: 2em;\n"
" text-align: center;\n"
" background: #7a7467;\n"
" padding-bottom: 0.5em;\n"
" padding-top: 0.5em;\n"
"}\n"
"\n"
"\n"
"/* If screen width >= */\n"
"@media only screen and (min-width: 1000px)\n"
"{\n"
" body\n"
" {\n"
" font-size: 1.5em;\n"
" width: 750px;\n"
" }\n"
" .top\n"
" {\n"
" font-size: 2em;\n"
" }\n"
"}\n"
"\n"
"\n"
".normal\n"
"{\n"
" font-size: 1.5em;\n"
"}\n"
"\n"
".main\n"
"{\n"
" margin-top: 1em;\n"
" margin-bottom: 0.0em;\n"
" font-size: inherit;\n"
"}\n"
"\n"
".banned\n"
"{\n"
" margin-top: 1em;\n"
" margin-bottom: 0.0em;\n"
" font-size: 120%;\n"
"}\n"
"\n"
"\n"
".answers\n"
"{\n"
" background: #a9a395;\n"
" border: 0.15em solid currentColor;\n"
" padding: .1em;\n"
" margin-top: .75em;\n"
" margin-left: 5%;\n"
" margin-right: 5%;\n"
" font-size: 1.75em;\n"
" /* align: center; */\n"
"}\n"
"\n"
;


const char checkbox_css[] PROGMEM = 
"input[type='checkbox'] \n"
"{\n"
" -moz-appearance: none;\n"
" -webkit-appearance: none;\n"
" appearance: none;\n"
" vertical-align: middle;\n"
" outline: none;\n"
" font-size: inherit;\n"
" cursor: pointer;\n"
" width: 1.0em;\n"
" height: 1.0em;\n"
" background: white;\n"
" border-radius: 0.25em;\n"
" border: 0.125em solid #555;\n"
" top: -0.1em;\n"
" position: relative;\n"
"}\n"
"\n"
"input[type='checkbox']:checked \n"
"{\n"
" background: #adf;\n"
"}\n"
"\n"
"input[type='checkbox']:checked:after \n"
"{\n"
" content: \"\\2714\";\n"
" position: absolute;\n"
" font-size: 90%;\n"
" left: 0.0625em;\n"
" top: -0.25em;\n"
"}"
;


const char legal_html[] PROGMEM = 
"<!DOCTYPE html>\n"
"<html lang=\"en\" dir=\"ltr\">\n"
"\n"
"<head>\n"
" <meta charset=\"utf-8\">\n"
" <title>BRC Open WiFi</title>\n"
" <link rel=\"stylesheet\" href=\"brc.css\">\n"
" <link rel=\"stylesheet\" href=\"checkbox.css\">\n"
" <script src=\"bmwifi.js\"></script>\n"
" <script src=\"questions.js\"></script>\n"
" <style>\n"
" .lic1\n"
" {\n"
" margin:0em 0em 0.5em;\n"
" font-family:Helvetica Neue,Helvetica,Arial,sans-serif;\n"
" line-height:1em;\n"
" }\n"
"\n"
" .licsmall\n"
" {\n"
" font-size:0.9em;\n"
" line-height:1em;\n"
" font-family:Helvetica Neue,Helvetica,Arial,sans-serif;\n"
" }\n"
" .lic18px\n"
" {\n"
" line-height:1em;\n"
" font-family:Helvetica Neue,Helvetica,Arial,sans-serif;\n"
" }\n"
" .liclist\n"
" {\n"
" padding:0em;\n"
" margin:0em 0px 0.5em 2em;\n"
" font-size:0.5em;\n"
" font-family:Helvetica Neue,Helvetica,Arial,sans-serif;\n"
" }\n"
" \n"
" .submit\n"
" {\n"
" font-size: 2em;\n"
" }\n"
" </style>\n"
"\n"
" <script>\n"
" function myOnload ()\n"
" {\n"
" console.log(\"onload\");\n"
" let title = getCookie (\"title\");\n"
" document.title = title;\n"
" setElementInnerText (\"top\", title);\n"
" }\n"
"\n"
"\n"
" function enable ()\n"
" {\n"
" agreeButton.disabled = !agreeChk.checked;\n"
" }\n"
" </script>\n"
"</head>\n"
"\n"
"<body onload=\"myOnload()\">\n"
" <div class=\"top centerHorizontal\" id=\"top\">\n"
" <!-- 750x1334 -->\n"
" BRC Open WiFi\n"
" </div>\n"
" <div class=\"main centerHorizontal\" id=\"main\">\n"
" <div dir=\"ltr\">\n"
" <p class=\"lic1\">\n"
" <small class=\"licsmall\"><b>Terms and Conditions</b></small></p>\n"
" <p class=\"licsmall\">\n"
" <small class=\"licsmall\">By using our internet service, you hereby assert that you\n"
" you are a burner and conduct yourself according to the ten priciples. You also acknowledge expressly acknowledge and agree that\n"
" there are significant security, privacy and confidentiality risks inherent in accessing or transmitting information through the internet, whether the connection is facilitated through wired or wireless technology. Security issues include, wi"
"thout limitation, interception of transmissions, loss of data, and the introduction or viruses and other programs that can corrupt or damage your computer.</small></p>\n"
" <p class=\"licsmall\">Accordingly, you agree that the owner and/or provider of this network is NOT liable for any interception or transmissions, computer worms or viruses, loss of data, file corruption, hacking or damage to your computer or other "
"devices that result from the transmission or download of information or materials through the internet service provided.</p>\n"
" <p class=\"licsmall\">Use of the wireless network is subject to the general restrictions outlined below. If abnormal, illegal, or unauthorized behavior is detected, including heavy consumption of bandwidth, the network provider reserves the right "
"to permanently disconnect the offending device from the wireless network.</p>\n"
" <p class=\"licsmall\"><b>Examples of Illegal Uses</b></p>\n"
" <p class=\"licsmall\">The following are representative examples only and do not comprise a comprehensive list of illegal uses:</p>\n"
" <ol class=\"liclist lic18px\">\n"
" <li >Spamming and invasion of privacy - Sending of unsolicited bulk and/or commercial messages over the Internet using the Service or using the Service for activities that invade another's privacy.</li>\n"
" <li >Intellectual property right violations - Engaging in any activity that infringes or misappropriates the intellectual property rights of others, including patents, copyrights, trademarks, service marks, trade secrets, or any other proprie"
"tary right of any third party.</li>\n"
" <li >Accessing illegally or without authorization computers, accounts, equipment or networks belonging to another party, or attempting to penetrate/circumvent security measures of another system. This includes any activity that may be used as"
" a precursor to an attempted system penetration, including, but not limited to, port scans, stealth scans, or other information gathering activity.</li>\n"
" <li >The transfer of technology, software, or other materials in violation of applicable export laws and regulations.</li>\n"
" <li >Export Control Violations</li>\n"
" <li >Using the Service in violation of applicable law and regulation, including, but not limited to, advertising, transmitting, or otherwise making available ponzi schemes, pyramid schemes, fraudulently charging credit cards, pirating softwar"
"e, or making fraudulent offers to sell or buy products, items, or services.</li>\n"
" <li >Uttering threats;</li>\n"
" <li >Distribution of pornographic materials to minors;</li>\n"
" <li >and Child pornography.</li>\n"
" </ol>\n"
" <p class=\"licsmall\"><b>Examples of Unacceptable Uses</b></p>\n"
" <p class=\"licsmall\">The following are representative examples only and do not comprise a comprehensive list of unacceptable uses:</p>\n"
" <ol class=\"liclist lic18px\">\n"
" <li>High bandwidth operations, such as large file transfers and media sharing with peer-to-peer programs (i.e.torrents)</li>\n"
" <li>Obscene or indecent speech or materials</li>\n"
"\n"
"\n"
" <li >High bandwidth operations, such as large file transfers and media sharing with peer-to-peer programs (i.e.torrents)</li>\n"
" <li >Obscene or indecent speech or materials</li>\n"
" <li >Defamatory or abusive language</li>\n"
" <li >Using the Service to transmit, post, upload, or otherwise making available defamatory, harassing, abusive, or threatening material or language that encourages bodily harm, destruction of property or harasses another.</li>\n"
" <li >Forging or misrepresenting message headers, whether in whole or in part, to mask the originator of the message.</li>\n"
" <li >Facilitating a Violation of these Terms of Use</li>\n"
" <li >Hacking</li>\n"
" <li >Distribution of Internet viruses, Trojan horses, or other destructive activities</li>\n"
" <li >Distributing information regarding the creation of and sending Internet viruses, worms, Trojan horses, pinging, flooding, mail-bombing, or denial of service attacks. Also, activities that disrupt the use of or interfere with the ability of "
"others to effectively use the node or any connected network, system, service, or equipment.</li>\n"
" <li >Advertising, transmitting, or otherwise making available any software product, product, or service that is designed to violate these Terms of Use, which includes the facilitation of the means to spam, initiation of pinging, flooding, mail-b"
"ombing, denial of service attacks, and piracy of software.</li>\n"
" <li >The sale, transfer, or rental of the Service to customers, clients or other third parties, either directly or as part of a service or product created for resale.</li>\n"
" <li >Seeking information on passwords or data belonging to another user.</li>\n"
" <li >Making unauthorized copies of proprietary software, or offering unauthorized copies of proprietary software to others.</li>\n"
" <li >Intercepting or examining the content of messages, files or communications in transit on a data network.\n"
" <li >Dorking about on the internet when you should be living in the moment</li>\n"
" </ol></div>\n"
"\n"
"\n"
" <form action=\"question.html\" method=\"post\" class=\"submit\">\n"
" <input type=\"checkbox\" name=\"checktest\" value=\"agree\" id=\"agreeChk\" onclick=\"enable()\">I Understand and Agree<br>\n"
" <input type=\"submit\" value=\"Submit\" id=\"agreeButton\" class=\"main\" onclick=\"getElementById('submitTimeStamp').value = new Date ().toISOString()\" disabled>\n"
" <input type=\"hidden\" id=\"submitTimeStamp\" name=\"timeStamp\" value=\"3487\">\n"
" </form>\n"
" </div>\n"
"\n"
"</body>\n"
"\n"
"</html>\n"
;


const char question_html[] PROGMEM = 
"<!DOCTYPE html>\n"
"<html lang=\"en\" dir=\"ltr\">\n"
" <!-- developer.mozilla.org/en-US/docs/Web/Guide/AJAX/Getting_Started -->\n"
" <head>\n"
" <meta charset=\"utf-8\">\n"
" <title>BRC Open WiFi</title>\n"
" <link rel=\"stylesheet\" href=\"brc.css\">\n"
" <link rel=\"stylesheet\" href=\"radio2.css\">\n"
" <script src=\"bmwifi.js\"></script>\n"
" <script src=\"questions.js\"></script>\n"
" <script src=\"debugdata.js\"></script>\n"
" <script>\n"
" function myOnload ()\n"
" {\n"
" let questionNumber = 0;\n"
" console.log(\"onload\");\n"
" let title = getCookie (\"title\");\n"
" document.title = title;\n"
" setElementInnerText (\"top\", title);\n"
"\n"
" questionNumber = getQuestionNumber ();\n"
" console.log (\"This is question \" + questionNumber);\n"
"\n"
" getQuestionSet ();\n"
"\n"
" /* solution.innerHTML = \"Screen \" + screen.width + \"x\"+ screen.height; */\n"
" }\n"
" </script>\n"
" </head>\n"
"\n"
" <body onload=\"myOnload()\">\n"
" <div class=\"top centerHorizontal\" id=\"top\">\n"
" BRC Open WiFi\n"
" </div>\n"
" <div class=\"main centerHorizontal\" id=\"main\">\n"
" <div id=\"questionDiv\">\n"
" Loading question set.\n"
" </div>\n"
" <div class=\"answers\">\n"
" <div id=\"optdiv0\" hidden>\n"
" <input type=\"radio\" id=\"optinput0\" name=\"answer\" value=\"0\" onclick=\"selectionChanged()\"/>\n"
" <label id=\"optlabel0\" for=\"optinput0\">0</label>\n"
" </div>\n"
" <div id=\"optdiv1\" hidden>\n"
" <input type=\"radio\" id=\"optinput1\" name=\"answer\" value=\"1\" onclick=\"selectionChanged()\"/>\n"
" <label id=\"optlabel1\" for=\"optinput1\">1</label>\n"
" </div>\n"
" <div id=\"optdiv2\" hidden>\n"
" <input type=\"radio\" id=\"optinput2\" name=\"answer\" value=\"2\" onclick=\"selectionChanged()\"/>\n"
" <label id=\"optlabel2\" for=\"optinput2\">2</label>\n"
" </div>\n"
" <div id=\"optdiv3\" hidden>\n"
" <input type=\"radio\" id=\"optinput3\" name=\"answer\" value=\"3\" onclick=\"selectionChanged()\"/>\n"
" <label id=\"optlabel3\" for=\"optinput3\">3</label>\n"
" </div>\n"
" <div id=\"optdiv4\" hidden>\n"
" <input type=\"radio\" id=\"optinput4\" name=\"answer\" value=\"4\" onclick=\"selectionChanged()\"/>\n"
" <label id=\"optlabel4\" for=\"optinput4\">3</label>\n"
" </div>\n"
" </div>\n"
" <div class=\"main\">\n"
" <button class=\"normal\" id=\"answerButton\" onclick=\"answerClick(getNextPage(),commentary)\" disabled value=\"Sub\">Answer</button> <span id=\"solution\" class=\"normal\"></span>\n"
" </div>\n"
" </div>\n"
" </body>\n"
"</html>\n"
;


const char questions_js[] PROGMEM = 
"{\n"
" var questionSet;\n"
" var answered = false;\n"
" function answerClick (nextPage, commentary)\n"
" {\n"
" console.log (nextPage);\n"
" console.log (commentary);\n"
" if (answered)\n"
" {\n"
" window.location.href = nextPage;\n"
" }\n"
" else\n"
" {\n"
" answered = true;\n"
" var correct = 0;\n"
" answerButton.innerHTML = \"Next\";\n"
" const inputs = document.getElementsByTagName (\"input\");\n"
" if (inputs != null)\n"
" {\n"
" for (var i=0; i<inputs.length; i++)\n"
" {\n"
" inputs[i].disabled = true;\n"
" if (inputs[i].dataset.correct == \"true\")\n"
" {\n"
" if (inputs[i].checked)\n"
" correct = 1;\n"
" inputs[i].parentNode.style.opacity = \"1.0\";\n"
" }\n"
" else\n"
" inputs[i].parentNode.style.opacity = \"0.1\";\n"
" }\n"
" }\n"
"\n"
" if (correct)\n"
" solution.innerHTML = \"Correct\";\n"
" else\n"
" solution.innerHTML = \"Sorry\";\n"
"\n"
" if (commentary != \"\")\n"
" solution.innerHTML += \" - \" + commentary;\n"
" }\n"
" }\n"
"\n"
" function selectionChanged ()\n"
" {\n"
" answerButton.disabled = false;\n"
" }\n"
"\n"
"\n"
" var nextQuestionPage;\n"
"\n"
" function getQuestionNumber ()\n"
" {\n"
" var qn = 0;\n"
" const queryString = window.location.search;\n"
" const urlParams = new URLSearchParams (window.location.search);\n"
" if (urlParams.get ('q') != null)\n"
" qn = Number (urlParams.get ('q'));\n"
"\n"
" if (isNaN (qn) || (qn < 0) || (questionSet == null) || (qn > (questionSet.length-1)))\n"
" qn = 0;\n"
"\n"
" return qn\n"
" }\n"
"\n"
" function getNextPage ()\n"
" {\n"
" let nextNumber = 1 + getQuestionNumber ();\n"
" let nextQuestionPage = \"question.html?q=\"+nextNumber;\n"
"\n"
" if (nextNumber >= questionSet.length)\n"
" nextQuestionPage = \"blocked.html\";\n"
"\n"
" return nextQuestionPage;\n"
" }\n"
"\n"
" const xhr = new XMLHttpRequest();\n"
" function ajaxHandler ()\n"
" {\n"
" if (xhr.readyState === XMLHttpRequest.DONE)\n"
" {\n"
" if (xhr.status === 200)\n"
" {\n"
" var data = JSON.parse (xhr.responseText);\n"
" questionSet = data;\n"
" displayQuestion (getQuestionNumber());\n"
" }\n"
" else\n"
" {\n"
" //alert('There was a problem with the request: ' + xhr.status);\n"
" }\n"
" }\n"
" }\n"
"\n"
" function getQuestionSet (qNumber)\n"
" {\n"
" displayQuestion (getQuestionNumber());\n"
"\n"
" if (window.location.protocol == \"file:\")\n"
" {\n"
" displayQuestion (getQuestionNumber());\n"
" }\n"
" else\n"
" {\n"
" const url = 'getJson';\n"
" var formData = new FormData();\n"
" formData.append (\"request\", \"question\");\n"
"\n"
" xhr.open ('POST', url, true);\n"
" xhr.onreadystatechange = ajaxHandler;\n"
" xhr.send (formData);\n"
" }\n"
" }\n"
"\n"
"\n"
" function displayQuestion (qn)\n"
" {\n"
" let questionData = questionSet[qn];\n"
"\n"
" answers = questionData.answers;\n"
" commentary = questionData.commentary;\n"
" questionDiv.innerText = questionData.question;\n"
"\n"
" for (let i=0; i<10; i++)\n"
" {\n"
" let optdiv = document.getElementById (\"optdiv\" + i);\n"
" if (optdiv != null)\n"
" optdiv.hidden = true;\n"
" }\n"
"\n"
" for (let i=0; i<answers.length; i++)\n"
" {\n"
" let optdiv = document.getElementById (\"optdiv\" + i);\n"
" let optlabel = document.getElementById (\"optlabel\" + i);\n"
" let optinput = document.getElementById (\"optinput\" + i);\n"
" if (optdiv != null)\n"
" {\n"
" optdiv.hidden = false;\n"
" optlabel.innerText = answers[i].text;\n"
" optinput.dataset.correct = answers[i].correct;\n"
"// if (optinput.dataset.correct == \"true\")\n"
"// optdiv.style.color = \"blue\";\n"
" }\n"
" }\n"
" }\n"
"\n"
"\n"
" // Randomize array in-place using Durstenfeld shuffle algorithm\n"
" function shuffleArray (array)\n"
" {\n"
" for (var i = array.length - 1; i > 0; i--)\n"
" {\n"
" var j = Math.floor(Math.random() * (i + 1));\n"
" var temp = array[i];\n"
" array[i] = array[j];\n"
" array[j] = temp;\n"
" }\n"
" }\n"
"}\n"
;


const char questions_json[] PROGMEM = 
"[\n"
" {\n"
" \"question\" : \"You need to demonstrate that you are a burner and not a robot. Which of the following is not one of the Ten Principles?\",\n"
" \"answers\" :\n"
" [\n"
" {\"correct\": true, \"text\" : \"Radical Self Entitlement\"},\n"
" {\"correct\": false, \"text\" : \"Radical Inclusion\"},\n"
" {\"correct\": false, \"text\" : \"Immediacy\"}\n"
" ],\n"
" \"commentary\" : \"Radical Self Entitlement is not a principle.\"\n"
" },\n"
" {\n"
" \"question\": \"Burning Man and the citizens of Black Rock City are dedicated to the Ten Principles. How many principles are there?\",\n"
" \"answers\" :\n"
" [\n"
" {\"correct\": false, \"text\": \"Trick question, there are only nine principles\"},\n"
" {\"correct\": true, \"text\": \"Ten\"},\n"
" {\"correct\": false, \"text\": \"Some other answer\"}\n"
" ],\n"
" \"commentary\" : \"\"\n"
" },\n"
" {\n"
" \"question\": \"Which people aren't covered by Radical Inclusion?\",\n"
" \"answers\" : \n"
" [\n"
" {\"correct\" : false, \"text\" : \"Shirt cockers\"},\n"
" {\"correct\" : false, \"text\" : \"Sparkle Ponies\"},\n"
" {\"correct\" : false, \"text\" : \"Plug & Play camps\"},\n"
" {\"correct\" : true, \"text\" : \"No one\"}\n"
" ],\n"
" \"commentary\" : \"\"\n"
" }\n"
"]\n"
"\n"
;


const char debugdata_js[] PROGMEM = 
"questionSet =\n"
"[\n"
" {\n"
" \"question\" : \"You need to demonstrate that you are a burner and not a robot. Which of the following is not one of the Ten Principles?\",\n"
" \"answers\" :\n"
" [\n"
" {\"correct\": true, text : \"Radical Self Entitlement\"},\n"
" {\"correct\": false, text : \"Radical Inclusion\"},\n"
" {\"correct\": false, text : \"Immediacy\"},\n"
" ],\n"
" \"commentary\" : \"Radical Self Entitlement is not a principle.\"\n"
" },\n"
" {\n"
" \"question\": \"Burning Man and the citizens of Black Rock City are dedicated to the Ten Principles. How many principles are there?\",\n"
" \"answers\" :\n"
" [\n"
" {\"correct\": false, text: \"Trick question, there are only nine principles\"},\n"
" {\"correct\": true, text: \"Ten\"},\n"
" {\"correct\": false, text: \"Some other answer\"},\n"
" ],\n"
" \"commentary\" : \"\"\n"
" }\n"
"];\n"
"\n"
"currentStatus =\n"
"{\n"
" \"redirects\" : 4,\n"
" \"banned\" : 1,\n"
" \"lastActivity\" : \"1980-01-01\",\n"
" \"iPhoneCount\" : 1,\n"
" \"androidCount\" : 2,\n"
" \"sdkVersion\" : \"0\",\n"
" \"bootVersion\" : 0,\n"
" \"chipID\" : \"0\",\n"
" \"cpuFreq\" : 10,\n"
" \"voltage\" : 10,\n"
" \"memoryFree\" : 0,\n"
" \"sketchSize\" : 0,\n"
" \"sketchFree\" : 0,\n"
" \"flashSize\" : 0,\n"
" \"flashSpeed\" : 0,\n"
" \"softApMac\" : \"a\",\n"
" \"softApIP\" : \"127\"\n"
"}\n"
;


const char radio2_css[] PROGMEM = 
"/* https://stackoverflow.com/questions/4920281/how-to-change-the-size-of-the-radio-button-using-css */\n"
"\n"
"input[type=\"radio\"]\n"
"{\n"
" -webkit-appearance: none;\n"
" -moz-appearance: none;\n"
" appearance: none;\n"
"\n"
" border-radius: 50%;\n"
" font: inherit;\n"
" width: 1em;\n"
" height: 1em;\n"
"\n"
" border: 0.15em solid currentColor;\n"
" transition: 0.2s all linear;\n"
" position: relative;\n"
" top: 0.1em;\n"
"}\n"
"\n"
"input[type=\"radio\"]:checked \n"
"{\n"
" border: .4em solid black;\n"
" outline: unset !important /* I added this one for Edge (chromium) support */\n"
"}"
;


const char banned_html[] PROGMEM = 
"<!DOCTYPE html>\n"
"<html lang=\"en\" dir=\"ltr\">\n"
"\n"
" <head>\n"
" <meta charset=\"utf-8\">\n"
" <title>BRC Open WiFi</title>\n"
" <link rel=\"stylesheet\" href=\"brc.css\">\n"
" <script src=\"bmwifi.js\"></script>\n"
" <script>\n"
" function myOnload ()\n"
" {\n"
" console.log(\"onload\");\n"
" let title = getCookie (\"title\");\n"
" document.title = title;\n"
" setElementInnerText (\"top\", title);\n"
"\n"
" getExpirationTime ();\n"
" }\n"
" </script>\n"
" </head>\n"
" <body onload=\"myOnload()\">\n"
" <script src=\"banned.js\"></script>\n"
"\n"
" <div class=\"top centerHorizontal\" id=\"top\">\n"
" BRC Open WiFi\n"
" </div>\n"
" <div class=\"banned centerHorizontal\" id=\"main\">\n"
" This device is currently BANNED for violation of the \n"
" Terms & Conditions which clearly listed \"Dorking about on the internet\" under\n"
" \"Examples of Unacceptable Uses\" as it is a violation of the principle of Immediacy.\n"
" </div>\n"
"\n"
" <div class=\"main centerHorizontal\">\n"
" The ban will expire in <span id=\"expire\">xx</span> minutes\n"
" </div>\n"
"\n"
" </body>\n"
"</html>\n"
"\n"
;


const char banned_js[] PROGMEM = 
" const xhr = new XMLHttpRequest();\n"
"\n"
" function expirationHandler ()\n"
" {\n"
" if (xhr.readyState === XMLHttpRequest.DONE)\n"
" {\n"
" if (xhr.status === 200)\n"
" {\n"
" let data = JSON.parse (xhr.responseText);\n"
" expire.innerHTML = data.expire;\n"
" }\n"
" else\n"
" {\n"
" //alert('There was a problem with the request: ' + xhr.status);\n"
" }\n"
" }\n"
" }\n"
"\n"
"\n"
" function getExpirationTime ()\n"
" {\n"
" const url = 'getJson';\n"
" var formData = new FormData();\n"
" formData.append (\"request\", \"expire\");\n"
"\n"
" xhr.open ('POST', url, true);\n"
" xhr.onreadystatechange = expirationHandler;\n"
" xhr.send (formData);\n"
" }\n"
"\n"
;


const char redirect_html[] PROGMEM = 
"<html>\n"
"\n"
"<head>\n"
" <meta charset=\"utf-8\">\n"
" <title>BRC Open WiFi</title>\n"
" <title>Network Authentication Required</title>\n"
" <meta http-equiv=\"refresh\" content=\"5; url=http://login.example.com/legal.html\">\n"
"</head>\n"
"\n"
"<body>\n"
" <p>You need to <a href=\"http://login.example.com/legal.html\"> authenticate with the local network</a> in order to gain access.</p>\n"
"</body>\n"
"\n"
"</html>\n"
;


const char status_html[] PROGMEM = 
"<!DOCTYPE html>\n"
"<html lang=\"en\" dir=\"ltr\">\n"
" <!-- developer.mozilla.org/en-US/docs/Web/Guide/AJAX/Getting_Started -->\n"
" <head>\n"
" <meta charset=\"utf-8\">\n"
" <title>BRC Open WiFi</title>\n"
" <link rel=\"stylesheet\" href=\"brc.css\">\n"
" <link rel=\"stylesheet\" href=\"radio2.css\">\n"
" <script src=\"bmwifi.js\"></script>\n"
" <script src=\"status.js\"></script>\n"
" <script src=\"debugdata.js\"></script>\n"
" <script>\n"
" function myOnload ()\n"
" {\n"
" console.log(\"onload\");\n"
" let title = getCookie (\"title\");\n"
" document.title = title;\n"
" setElementInnerText (\"top\", title);\n"
"\n"
" getStatus ();\n"
" }\n"
" </script>\n"
" </head>\n"
"\n"
" <body onload=\"myOnload()\">\n"
" <div class=\"top centerHorizontal\" id=\"top\">\n"
" BRC Open WiFi\n"
" </div>\n"
" <div class=\"main centerHorizontal\" id=\"main\">\n"
" <table>\n"
" <tr><td>Requests: </td><td id=\"requests\"></td></tr>\n"
" <tr><td>Banned: </td><td id=\"banned\"></td></tr>\n"
" <tr><td>Last Activity: </td><td id=\"lastActivity\"></td></tr>\n"
"\n"
" <tr><td>Android: </td><td id=\"androidCount\"></td></tr>\n"
" <tr><td>iPhone: </td><td id=\"iPhoneCount\"></td></tr>\n"
" <tr><td>&nbsp;</td> </tr>\n"
" <tr><td>SDK Version: </td><td id=\"sdkVersion\"></td></tr>\n"
" <tr><td>Boot Version: </td><td id=\"bootVersion\"></td></tr>\n"
" <tr><td>Chip ID: </td><td id=\"chipID\"></td></tr>\n"
" <tr><td>CPU Freq: </td><td id=\"cpuFreq\"></td></tr>\n"
" <tr><td>Voltage: </td><td id=\"voltage\"></td></tr>\n"
" <tr><td>Free Heap: </td><td id=\"memoryFree\"></td></tr>\n"
" <tr><td>Sketch Size: </td><td id=\"sketchSize\"></td></tr>\n"
" <tr><td>Sketch Free: </td><td id=\"sketchFree\"></td></tr>\n"
" <tr><td>Flash Size: </td><td id=\"flashSize\"></td></tr>\n"
" <tr><td>Soft AP Mac: </td><td id=\"softApMac\"></td></tr>\n"
" <tr><td>Soft AP IP: </td><td id=\"softApIP\"></td></tr>\n"
" </table>\n"
" </div>\n"
"\n"
" </body>\n"
"</html>\n"
;


const char status_js[] PROGMEM = 
"{\n"
"var questionSet;\n"
"var currentStatus;\n"
"\n"
" const xhr = new XMLHttpRequest();\n"
" function ajaxHandler ()\n"
" {\n"
" if (xhr.readyState === XMLHttpRequest.DONE)\n"
" {\n"
" if (xhr.status === 200)\n"
" {\n"
" var data = JSON.parse (xhr.responseText);\n"
" currentStatus = data;\n"
" displayStatus ();\n"
" }\n"
" else\n"
" {\n"
" //alert('There was a problem with the request: ' + xhr.status);\n"
" }\n"
" }\n"
" }\n"
"\n"
"\n"
"\n"
" function getStatus ()\n"
" {\n"
" if (window.location.protocol == \"file:\")\n"
" {\n"
" displayStatus ();\n"
" }\n"
" else\n"
" {\n"
" const url = 'getJson';\n"
" var formData = new FormData();\n"
" formData.append (\"request\", \"status\");\n"
"\n"
" xhr.open ('POST', url, true);\n"
" xhr.onreadystatechange = ajaxHandler;\n"
" xhr.send (formData);\n"
" }\n"
" }\n"
"\n"
"\n"
" function displayStatus ()\n"
" {\n"
" setElementInnerText (\"requests\", currentStatus.redirects);\n"
" setElementInnerText (\"banned\", currentStatus.banned);\n"
" setElementInnerText (\"lastActivity\", currentStatus.lastActivity);\n"
"\n"
" setElementInnerText (\"iPhoneCount\", currentStatus.iPhoneCount);\n"
" setElementInnerText (\"androidCount\", currentStatus.androidCount);\n"
"\n"
" setElementInnerText (\"sdkVersion\", currentStatus.sdkVersion);\n"
" setElementInnerText (\"bootVersion\", currentStatus.bootVersion);\n"
" setElementInnerText (\"chipID\", currentStatus.chipID);\n"
" setElementInnerText (\"cpuFreq\", currentStatus.cpuFreq);\n"
" setElementInnerText (\"voltage\", currentStatus.voltage);\n"
" setElementInnerText (\"memoryFree\", currentStatus.memoryFree);\n"
" setElementInnerText (\"sketchSize\", currentStatus.sketchSize);\n"
" setElementInnerText (\"sketchFree\", currentStatus.sketchFree);\n"
" setElementInnerText (\"flashSize\", currentStatus.flashSize);\n"
" setElementInnerText (\"softApMac\", currentStatus.softApMac);\n"
" setElementInnerText (\"softApIP\", currentStatus.softApIP);\n"
" }\n"
"}\n"
;


const char bmwifi_js[] PROGMEM = 
"function setElementInnerText(elementID, innerText)\n"
"{\n"
" let id = document.getElementById(elementID);\n"
" if (id != null)\n"
" id.innerText = innerText;\n"
"}\n"
"\n"
"\n"
"function getCookie(cName)\n"
"{\n"
" const name = cName + \"=\";\n"
" console.log (document.cookie);\n"
" const cDecoded = decodeURIComponent(document.cookie);\n"
" console.log (cDecoded);\n"
" const cArr = cDecoded.split('; ');\n"
" let res;\n"
" cArr.forEach(val =>\n"
" {\n"
" if (val.indexOf(name) === 0) res = val.substring(name.length);\n"
" })\n"
" return res\n"
"}\n"
;
